### ISSUE TITLE
scopes of access tokens in config

### ISSUE THREAD

**Issue by schleichardt** [sphereio/sphere-jvm-sdk#1045]
* [x] support other scopes than manage_projects
* [x] also document exceptions/errors
* [x] customer password flow
* [x] enhance SphereAuthConfig
* [x] enhance SphereClientConfig
* [x] examples on method
* [x] SphereClientConfigBuilder
* [x] SphereAuthConfigBuilder
* [x] remove of scope methods
* [x] properties include scopes
* [x] env include scopes

**Comment by cneijenhuis** [comment]
FYI: Thanks to @yanns it is now possible to create OAuth clients with different scopes in the MC :+1:
