### ISSUE TITLE
Implement orders

### ISSUE THREAD

**Issue by schleichardt** [sphereio/sphere-jvm-sdk#159]
http://dev.sphere.io/http-api-projects-orders.html

* [x] Order
* [x]  OrderState
* [x]  ShipmentState
* [x]  PaymentState
* [x]  ReturnShipmentState
* [x]  ReturnPaymentState
* [x]  SyncInfo
* [x]  ReturnInfo
* [x]  ReturnItem
* [x]  Delivery
* [x]  DeliveryItem
* [x]  Parcel
* [x]  ParcelMeasurements
* [x]  TrackingData
* [x]  ItemState
* [x]  Get Order by ID
* [ ]  Query Orders
    * [x] customerId
    * [x] customerEmail
    * [x] country
    * [ ] totalPrice (not in 1.0.0)
    * [ ] taxedPrice (not in 1.0.0)
    * [ ] shippingAddress (not in 1.0.0)
    * [ ] billingAddress (not in 1.0.0)
    * [ ] customerGroup (not in 1.0.0
    * [x] orderState (later)
    * [x] shipmentState (later)
    * [x] paymentState (later)
    * [x] syncInfo (later)
    * [ ] returnInfo (later)
    * [ ] lineItems (later)
    * [ ] customLineItems (later)
* [x]  Create Order from a Cart
    * [ ]  OutOfStock
    * [ ]  PriceChanged
* [x]  Create Order by Import
* [x]  Update Order
* [x]  Change Order State
* [x]  Change Shipment State
* [x]  Change Payment State
* [x]  Update Sync Info
* [x]  Add a Return Info
* [x]  Set ReturnShipmentState
* [x]  Set ReturnPaymentState
* [x]  Change the state of a Line Item according to allowed transitions
* [x]  Change the state of a Custom Line Item according to allowed transitions
* [x]  Import a state for Line Items
* [x] Import a state for Custom Line Items
* [x]  Add a Delivery
* [x]  Add a Parcel
* [x]  Set Order Number

**Comment by schleichardt** [comment]
@mmoelli Could you help me to find the typical use cases to query for orders, please?
I want to know, what should be there in 1.0.0. 

I expect a list with sth like this:
* query orders by a customer
* query orders which are in state pending

**Comment by butenkor** [comment]
- Orders with payment status paid but not exported yet (export state)

- Orders with pagination
