### ISSUE TITLE
Use factory or builder to instantiate JavaClient

### ISSUE THREAD

**Issue by schleichardt** [sphereio/sphere-jvm-sdk#177]
* [x] client with just token, without credentials (clientsecret) at all
* [x] urls for prject-ws and auth-ws configurable
* [x] remove typesafe conf dependency
* [x] document testing verbosely
* [x] different oauth scope and exception for missing rights//API does not support it for now
* [ ] whole package review
* [x] update Scala addons, other clients should take the java client as parameter
* [x] exception enrichment for test doubles
* [x] we should add a real world example where the credentials are either env variables or read from a config file (.properties?). + typesafe config
* [x] check if test double with SphereRequest is okay 
* [x] java-client-core project without dependency to HTTP client, use java-client project for factory using async http client

**Comment by lauraluiz** [comment]
`different oauth scope and exception for missing rights` <- I totally add 2 votes for that

**Comment by schleichardt** [comment]
The backend supports only manage-project, the website documentation is inaccurate.

**Comment by schleichardt** [comment]
```

    public SphereClient createObjectTestDouble(final Function<Requestable, Object> function) {
        return new SphereClient() {
            @Override
            public <T> CompletableFuture<T> execute(final SphereRequest<T> sphereRequest) {
                final T result = (T) function.apply(sphereRequest);
                final CompletableFuture future = new CompletableFuture();
                future.complete(result);
                return future;
            }

            @Override
            public void close() {
            }

            @Override
            public String toString() {
                return "SphereClientObjectTestDouble";
            }
        };
    }
```

**Comment by schleichardt** [comment]
@AndreasKl see above, to match via a SphereRequest (previously called ClientRequest)

**Comment by yanns** [comment]
@schleichardt maybe a valuable information for you:
My use case when deploying a sphere-based application to Heroku:
- I configured everything expect the clientSecret in a configuration file.
- I configure the clientSecret in an environment variable to avoid putting it in the file.
https://github.com/yanns/talks/blob/master/app/globals/Token.scala#L81

**Comment by nkuehn** [comment]
by Michael
