### ISSUE TITLE
create good exception hierarchy

### ISSUE THREAD

**Issue by schleichardt** [sphereio/sphere-jvm-sdk#191]
As a SDK user,
I want to use specific exception classes for SPHERE.IO related errors on client and server side,
so that is possible to define specific error handlers while working the the SDK.

* [x] install graphviz in travis
* [x]  for example bundled by 4xx, 5xx
* [x]  show image with hierarchy
* [ ]  check the possablity that 3xx responses also okay
* [x]  improve names of HttpResponse code helpers (hasXyzStatusCode) -> is2xxResponseCode()
* [ ] check SPHERE backend validations, like SameForAll constraint

**Comment by AndreasKl** [comment]
Could be an inspiration: https://github.com/undertow-io/undertow/blob/master/core/src/main/java/io/undertow/client/UndertowClientMessages.java
