### ISSUE TITLE
Add exercises to tutorial pages

### ISSUE THREAD

**Issue by schleichardt** [sphereio/sphere-jvm-sdk#192]
@lauraluiz should we add exercises with hidden solutions (click to reveal) to the tutorial pages to help to learn the SDK?

For example ask how to query for a specific things.

**Comment by hajoeichler** [comment]
Nice idea

**Comment by lauraluiz** [comment]
We can have a section for this, like in w3schools, I like that. But I wouldn't put it within the documentation (links to the quizzes are okay, of course).

**Comment by schleichardt** [comment]
will never have time to do this

**Comment by lauraluiz** [comment]
Reality just dropped like a bucket of chill water :D
