### ISSUE TITLE
Implement InventoryEntries

### ISSUE THREAD

**Issue by mmoelli** [sphereio/sphere-jvm-sdk#193]
http://dev.sphere.io/http-api-projects-inventory.html

* [x] InventoryEntry
* [x] Query Inventory
* [x] query model
* [x] Get Inventory Entry by ID
* [x] Create an Inventory Entry
* [x] Update an Inventory Entry
    * [x] addQuantity
    * [x] removeQuantity
    * [x] setRestockableInDays
    * [x] setExpectedDelivery

* [x] delete

**Comment by AndreasKl** [comment]
+1
