### ISSUE TITLE
ImageDimensions does not match JSON API

### ISSUE THREAD

**Issue by mgm-jmatz** [sphereio/sphere-jvm-sdk#208]
Version 1.0.0-M9:
I tried to upload an external Image by implementing my own AddExternalImage action. This action required an Image which again required an ImageDimension.

When using io.sphere.sdk.models.ImageDimensions I got the following response from SphereIO:

`sphere request: io.sphere.sdk.client.CachedHttpRequestClientRequest@6ef12db8[delegate=io.sphere.sdk.products.commands.ProductUpdateCommand@e7c8c36[versioned=io.sphere.sdk.models.SimpleVersioned@a55de24[id=90f2f671-13f8-43f7-a193-c5013767bc15,version=1],updateActions=[productimporter.sphere.updateactions.AddExternalImageBuggy@2dde8ca6[variantId=1,image=io.sphere.sdk.models.ImageImpl@5ceec6ee[url=https://d9gkwhfwam31p.cloudfront.net/0084913/5196500_lightbox.png,dimensions=io.sphere.sdk.models.ImageDimensions@786e97a9[width=0,height=0],label=Optional.empty],action=addExternalImage]],typeReference=TypeReference<Product>,baseEndpointWithoutId=/products],httpRequest=io.sphere.sdk.http.JsonBodyHttpRequestImpl@7cd96470[body={"version":1,"actions":[{"action":"addExternalImage","variantId":1,"image":{"url":"https://d9gkwhfwam31p.cloudfront.net/0084913/5196500_lightbox.png","dimensions":{"width":0,"height":0},"label":null}}]},httpMethod=POST,path=/products/90f2f671-13f8-43f7-a193-c5013767bc15,headers=io.sphere.sdk.http.HttpHeaders@ed73c20[headers={}]]]
underlying http request: POST /products/90f2f671-13f8-43f7-a193-c5013767bc15
{
  "version" : 1,
  "actions" : [ {
    "action" : "addExternalImage",
    "variantId" : 1,
    "image" : {
      "url" : "https://d9gkwhfwam31p.cloudfront.net/0084913/5196500_lightbox.png",
      "dimensions" : {
        "width" : 0,
        "height" : 0
      },
      "label" : null
    }
  } ]
}
underlying http response: status=400 body={{"statusCode":400,"message":"Request body does not contain valid JSON.","errors":[{"code":"InvalidJsonInput","message":"Request body does not contain valid JSON.","detailedErrorMessage":"actions -> image -> dimensions -> w: Missing required value"},{"code":"InvalidJsonInput","message":"Request body does not contain valid JSON.","detailedErrorMessage":"actions -> image -> dimensions -> h: Missing required value"}]}}
detailMessage: Error response from Sphere: /products/90f2f671-13f8-43f7-a193-c5013767bc15
[400]
  io.sphere.sdk.client.SphereError@27c63bfc[code=InvalidJsonInput,message=Request body does not contain valid JSON.]`

**Comment by schleichardt** [comment]
see https://github.com/sphereio/sphere-jvm-sdk/pull/206

**Comment by mgm-jmatz** [comment]
Looks good to me. 
And there is already an AddExternalImage action. Great!
Thanks.
