### ISSUE TITLE
add class ProductVariantIdentifier

### ISSUE THREAD

**Issue by schleichardt** [sphereio/sphere-jvm-sdk#225]
```
public class ProductVariantIdentifier extends Base {
     private final String productId;
     private final long variantId;
     //getters [...]
{
```

@lauraluiz What do you think of it? Or should it be named VariantIdentifier?

Maybe we could use a class which also has a quantity.
io.sphere.sdk.carts.commands.updateactions.AddLineItem does this already.

* check if it can be a getter in the variant (hacking product id in it)

**Comment by hajoeichler** [comment]
I vote for `VariantIdentifier`

**Comment by lauraluiz** [comment]
I really like this class as it is. But I cannot think of an usage of the quantity inside a class like this in an app. With AddLineItem is needed for creating the line item, but it doesn't apply to variants, does it?

**Comment by schleichardt** [comment]
ok
