### ISSUE TITLE
Exception classes should show example cases when they could occur

### ISSUE THREAD

**Issue by schleichardt** [sphereio/sphere-jvm-sdk#237]

**Comment by emmenko** [comment]
You mean for the documentation?

**Comment by schleichardt** [comment]
yes

**Comment by lauraluiz** [comment]
And do we have a place where I can check, for example, which exceptions can occur when executing the CustomerSignInCommand?

**Comment by schleichardt** [comment]
I think this should be directly documented in the class.

But I want also a bit picture of exceptions.

**Comment by schleichardt** [comment]
I think the exception hierarchy is so flat, this will be clear.
