### ISSUE TITLE
Freetext search on product data yields unexpected results with unicode characters

### ISSUE THREAD

**Issue by AndreasKl** [sphereio/sphere-jvm-sdk#240]
If a `ProductProjectionSearch#withText` for a german umlaut is executed the search does not include words with the umlaut in the result set.

This ticket is mostly for tracking purposes as this could be a backend issue.

**Comment by schleichardt** [comment]
I could reproduce and tried to make a workaround:

Copy this class in the right package in your codebase https://gist.github.com/schleichardt/d8b3a9e1f82776fa7403

Usage: 
```
final SearchDsl<ProductProjection> underlying = ProductProjectionSearch.of(ProductProjectionType.STAGED).withText(GERMAN, "öón");
final Search<ProductProjection> useThisForExecute = Bug240Workaround.of(underlying);
```

**Comment by schleichardt** [comment]
Sorry, it is a bug inherited from the Play SDK.
