### ISSUE TITLE
Limit the amount of requests to SPHERE.IO

### ISSUE THREAD

**Issue by schleichardt** [sphereio/sphere-jvm-sdk#247]
* it could be solved with a decorator http://en.wikipedia.org/wiki/Decorator_pattern to adjust it for the project
* Inspirations:
    * https://asynchttpclient.github.io/async-http-client/apidocs/reference/com/ning/http/client/extra/ThrottleRequestFilter.html
    * https://github.com/sphereio/sphere-node-sdk/blob/master/docs/TASK-QUEUE.md

**Comment by schleichardt** [comment]
It is possible, that a delegate packs the SphereRequest and the a future for the response into a queue and returns the future to the client, so at least from outside it is non blocking.

**Comment by emmenko** [comment]
:+1:

**Comment by OlegIlyenko** [comment]
I would also consider this config property of async-http-client, that allows to limit the amount of HTTP connection per host:

https://github.com/AsyncHttpClient/async-http-client/blob/master/api/src/main/java/org/asynchttpclient/AsyncHttpClientConfig.java#L72

**Comment by schleichardt** [comment]
Cool, it would be nice in general to inject the client, to set things like timouts.

**Comment by OlegIlyenko** [comment]
yeah, ideally it would be nice to allow end-users to customize any part of the async-http-client config to their needs

**Comment by sam0r** [comment]
I agree, the current implementation is very restricitve for end-users. Having a possibility to customize the async-http-client would be great.

**Comment by schleichardt** [comment]
@OlegIlyenko @lauraluiz 

Here is a gist for a very <strong>simple</strong> request blocking mechanism:

https://gist.github.com/schleichardt/6728d9ad316726261d30

Of cause for the next release it is the goal to enable the http client configuration.

**Comment by Niondir** [comment]
The gist is not working in some scenarios where you run into nested futures. We have currently two places where it fails:
1) Getting all Products via Pagination to delete them
2) Adding multiple images to a Product after it was created

Somewhere something gets blocked there, we did not found the cause for it yet. But investing time seems wasted when making the httpClient public/configurable would solve all problems.

**Comment by schleichardt** [comment]
Maybe it is related to the future composition, 
there is thenApply https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/CompletableFuture.html#thenApply-java.util.function.Function-
and thenApplyAsync (the same for other methods) https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/CompletableFuture.html#thenApplyAsync-java.util.function.Function-

If you use async you may not run into problems. We currently work on better solutions.

**Comment by Niondir** [comment]
Btw. just found that the HttpClient solution might not be good, since it just throws an exception:
https://github.com/AsyncHttpClient/async-http-client/blob/master/providers/netty3/src/main/java/org/asynchttpclient/providers/netty3/channel/ChannelManager.java#L329

**Comment by schleichardt** [comment]
Thanks, good to know.

I want also to provide a http client independent solution, which wraps the SphereClient, returns a future, but does only execute x requests without having the answer at the same time, something like a queue.

**Comment by schleichardt** [comment]
Will be available in the next release (soon) http://sphereio.github.io/sphere-jvm-sdk/javadoc/master/io/sphere/sdk/meta/ReleaseNotes.html#v1_0_0_M11
