### ISSUE TITLE
Document typical traps

### ISSUE THREAD

**Issue by schleichardt** [sphereio/sphere-jvm-sdk#262]
* [ ] plus sort may not have the desired effect, since default sort is by ID
* product data traps (current/staged)

**Comment by hajoeichler** [comment]
Is the default sorting by ID done by the SDK?

**Comment by schleichardt** [comment]
Yes, by default you sort by ID.

**Comment by schleichardt** [comment]
we removed the default sort by id functionality, typical traps should be documented on the dev website.
