### ISSUE TITLE
Name query-related Sort classes to QuerySort

### ISSUE THREAD

**Issue by lauraluiz** [sphereio/sphere-jvm-sdk#267]
Change the classes in the `query` package named Sort, SortBase, SortDirection, SimpleSort, SortingModel... to QuerySort, QuerySortBase, QuerySortDirection, QuerySimpleSort... etc.

In the `search` package all of them are SearchSort, etc.

**Comment by schleichardt** [comment]
@lauraluiz Can you do this?
