### ISSUE TITLE
Incosistent type of VariantId

### ISSUE THREAD

**Issue by StephanWels** [sphereio/sphere-jvm-sdk#294]
The ProductVariant Interface exposes the `ProductVariant` as `Long`, while the `AddLineItem` UpdateAction expects the ProductVariant to be `int`
```java
public interface ProductVariant {

    public long getId();
    [...]
}
```

```java
public class AddLineItem extends UpdateAction<Cart> {
	
    public static AddLineItem of(final String productId, final int variantId,
                              final long quantity) {
        return new AddLineItem(productId, variantId, quantity);
    }
    [...]
}
```

**Comment by schleichardt** [comment]
Thanks for pointing this out, it is very hard to find this kind of issues.
In the current release (1.0.0-M11) this is fixed:

http://sphereio.github.io/sphere-jvm-sdk/javadoc/v1.0.0-M11/io/sphere/sdk/products/ProductVariant.html#getId--

http://sphereio.github.io/sphere-jvm-sdk/javadoc/v1.0.0-M11/io/sphere/sdk/carts/commands/updateactions/AddLineItem.html#getVariantId--
