### ISSUE TITLE
Categories: Changing a category to a root category not possible

### ISSUE THREAD

**Issue by sam0r** [sphereio/sphere-jvm-sdk#302]
Hi,

when changing the parent category of an existing category with the ChangeParent UpdateAction to null (thus trying to make it a root category, there is currently a null pointer thrown. Passing an empty string gives me an invalid json error from sphere.

How can I set the parent to of ca category to null to make it a root category?

Thanks in advance

**Comment by schleichardt** [comment]
Yes, the SDK is not intended to pass null as parameter anywhere, we use Optional to signal, that there can be a value missing.

The SDK classes are according the API, currently it is not possible to make a category with a parent a root category. So you need to delete the category and create a new category without a parent.

I will report this issue to the product team.

**Comment by stmeissner** [comment]
@sam0r your question is related to the SPHERE.IO platform.
Can I kindly ask you contact SPHERE.IO support on http://support.sphere.io/ 

thanks
