### ISSUE TITLE
QueueSphereClientDecoratorActor is using not threadsafe Queue

### ISSUE THREAD

**Issue by Niondir** [sphereio/sphere-jvm-sdk#306]
I just took a look into the ```QueueSphereClientDecorator```. ```actor.tell(asyncTask);``` eventually get called from multiple threads and eventually add the task to be executed to the ```Queue<AsyncTask> queuedTasks = new LinkedList<>();```

Where the documentation says:
```
    <strong>Note that this implementation is not synchronized.</strong>
    * If multiple threads access a linked list concurrently, and at least
    * one of the threads modifies the list structurally, it <i>must</i> be
    * synchronized externally.
```

I would strongly recommend to use some async queue e.g. ```LinkedTransferQueue``` or ```LinkedBlockingQueue```

The semaphore client had it's issues and we came up with the following much shorter implementation to limit the requests based on some well established JDK solution:

```
public class QueuingSphereClient implements SphereClient {
    private final SphereClient delegate;

    private final BlockingQueue<Runnable> blockingQueue = new ArrayBlockingQueue<>(100000);
    private final ThreadPoolExecutor threadPoolExecutor;

    public QueuingSphereClient(final SphereClient delegate, final int limit) {
        this.delegate = delegate;
        threadPoolExecutor = new ThreadPoolExecutor(limit, limit, 20L, TimeUnit.SECONDS, blockingQueue);
    }

    @Override
    public void close() {
        delegate.close();
    }

    @Override
    public <T> CompletableFuture<T> execute(final SphereRequest<T> clientRequest) {
        final CompletableFuture<T> future = CompletableFuture.supplyAsync(() -> delegate.execute(clientRequest).join(), threadPoolExecutor);
        return future;
    }
}
```

This could be even easier by just taking a ```ForkJoinPool(int parallelism)``` where parallelism is the number of max concurrent requests. The ForkJoinPool also has some queuing internally. But I did not tested that yet.

**Comment by schleichardt** [comment]
Thanks, I will have a look.
`() -> delegate.execute(clientRequest).join()` is blocking a thread, we try to do non blocking programming.

**Comment by schleichardt** [comment]
In the class `QueueSphereClientDecoratorActor` is a member `queuedTasks` but since I am in an actor, I can use not synchronized elements, since the Actor is only executed in one Thread.

The synchronisation is done in the Actor class with `executor.execute(() -> receive(message));`.

**Comment by Niondir** [comment]
Thanks for the explanations it was a bit hidden :) But quiet nice.

Yep, it in fact the other solution blocks some threads, it leads to upto ```maxRequests``` worker threads that actively wait for the requests to finish. That's much nicer with the Actor approach.

**Comment by schleichardt** [comment]
So the implementation is okay and the issue can be closed?

**Comment by Niondir** [comment]
Yep, just doing it. Thanks.
