### ISSUE TITLE
Transfer an order back into a cart

### ISSUE THREAD

**Issue by AndreasKl** [sphereio/sphere-jvm-sdk#309]
Currently there is no sophisticated way to transfer an order back into an cart. This would be nice for the following scenario:

If a customer does a checkout we would like to be always on the safe side and transfer his cart into an order before we finally seize the money. If the final money transfer fails we would like to show a nice error message and transfer the order back into a cart. Currently we have to do this by hand (address, line items ....) however we would like to see this as a backend functionality.

**Comment by emmenko** [comment]
Aside from the SDK, if a `Cart` is transformed into an `Order` there is no going back (this is by design as an `Order` cannot be "modified" after being created).

Question: why do you want to create the `Order` before payment is done? What's the safe side on that? And why can't you keep the `Cart` until payment is successful?

**Comment by AndreasKl** [comment]
HTTP Request can and will fail (even after retrying for hours) so I never would like to get in an scenario where a customer paid and we do not have an order. Therefore I prefer to have (in this rare scenario) a cancelled order instead of having a cart somewhere. 

I`m not asking about a way to undo the conversion from cart to an order just for a more convenient way to create an cart from an existing order.

If think this is still an odd scenario then another use case: A customer would like to reorder his pervous order.

**Comment by emmenko** [comment]
Yes, I guess it could be possible. We have to discuss this internally first, but it would help if you create a feature request here http://support.sphere.io/forums/201737-api

**Comment by lauraluiz** [comment]
I agree with @AndreasKl, this is a necessary feature since it has always been a weakness of the system not being able to revert an order cleanly when dealing with the checkout process. This is definitely something that the backend should take care of, and not the SDK and even less the developer.

**Comment by butenkor** [comment]
Would be nice indeed, but one has to consider also that creating a cart from existing order (in this particular case: failed payment) does not release stock which has been reserved on existing order. It means that your new cart may not have all the items like before. There could be also issues with applied  discounts which would not apply to new cart anymore.

**Comment by emmenko** [comment]
@butenkor right, we should also consider that. I would recommend to move the discussion in the support forum.

http://support.sphere.io/forums/201737-api
