### ISSUE TITLE
Java client for ning 1.9.x

### ISSUE THREAD

**Issue by schleichardt** [sphereio/sphere-jvm-sdk#310]
@lauraluiz If it really helps you, I can do it today.

**Comment by lauraluiz** [comment]
Let's leave it for the future, I don't really need it now as it works (even though the code is uglier).

**Comment by schleichardt** [comment]
Needed for Play 2.4

**Comment by schleichardt** [comment]
should be default client

**Comment by schleichardt** [comment]
https://github.com/sphereio/sphere-jvm-sdk/commit/2e77f9b15bf402afadfedb881144b692f2616077
