### ISSUE TITLE
Check all Impl classes for JSON creator

### ISSUE THREAD

**Issue by schleichardt** [sphereio/sphere-jvm-sdk#322]
`No suitable constructor found for type [simple type, class io.sphere.sdk.products.ProductVariantAvailabilityImpl`

**Comment by lauraluiz** [comment]
Fixed fd0792c844156b4bf4498b0d125c920d2bc61c1c

**Comment by schleichardt** [comment]
Please don't close the tickets, I want to look for more open issues concerning this.

**Comment by lauraluiz** [comment]
I know, I was not going to. Just to point out that this particular one was fixed :)
