### ISSUE TITLE
Incorporate Java Streams to API

### ISSUE THREAD

**Issue by schleichardt** [sphereio/sphere-jvm-sdk#325]
It would be interesting to use [Streams](https://docs.oracle.com/javase/8/docs/api/java/util/stream/Stream.html) for the Query API, for example for cases where every object needs to be fetched.

`public static <T> Stream<T> streamAll(SphereClient client, QueryDsl<T> query)`

**Comment by schleichardt** [comment]
A problem is the blocking nature of Streams.

**Comment by emmenko** [comment]
Why are they blocking?

**Comment by schleichardt** [comment]
Because a future.join() is necessary to wait for the results.

**Comment by emmenko** [comment]
Hmm, here it says it's not a problem since all futures have already completed

```java
private static <T> CompletableFuture<List<T>> sequence(List<CompletableFuture<T>> futures) {
    CompletableFuture<Void> allDoneFuture =
        CompletableFuture.allOf(futures.toArray(new CompletableFuture[futures.size()]));
    return allDoneFuture.thenApply(v ->
            futures.stream().
                    map(future -> future.join()).
                    collect(Collectors.<T>toList())
    );
}
```
> Watch carefully sequence() argument and return types. The implementation is surprisingly simple, the trick is to use existing allOf() but when allDoneFuture completes (which means all underlying futures are done), simply iterate over all futures and join() (blocking wait) on each. **However this call is guaranteed not to block because by now all futures completed!**

Am I missing something? ...just would like to understand :)

**Comment by schleichardt** [comment]
CompletableFuture.sequence is useful if you want to load all your data into the RAM, if you want to proceed one after another this is not an option.

**Comment by emmenko** [comment]
Ah ok, thanks.

**Comment by schleichardt** [comment]
We have reactive streams: http://sphereio.github.io/sphere-jvm-sdk/javadoc/master/io/sphere/sdk/queries/ExperimentalReactiveStreamUtils.html
