### ISSUE TITLE
There is no way to create a product with images in one call

### ISSUE THREAD

**Issue by hajoeichler** [sphereio/sphere-jvm-sdk#336]
I have to create a second call to add the images to a product.

**Comment by hajoeichler** [comment]
It's the API that does not store the images during creation.

**Comment by schleichardt** [comment]
Do you mean upload image or external link or both?

**Comment by schleichardt** [comment]
So, it is HTTP API related and I can close the ticket?

**Comment by hajoeichler** [comment]
Yes.
