### ISSUE TITLE
It's possible to create products using the API that can not be edited in the MC

### ISSUE THREAD

**Issue by Niondir** [sphereio/sphere-jvm-sdk#341]
Create a product without a name and with a required Text field left empty. This is possible with the API.

Now go to the UI and try to edit the product, you will always get a validation error that you can't fix because both attributes are on different tabs in the MC.

**Comment by Niondir** [comment]
Some images as proof:

![image](https://cloud.githubusercontent.com/assets/373559/7048903/efca3374-de15-11e4-8c01-eccfef6b3d47.png)
![image](https://cloud.githubusercontent.com/assets/373559/7048916/ffdede9a-de15-11e4-854b-c6df768d3d14.png)
![image](https://cloud.githubusercontent.com/assets/373559/7048924/08ae72ce-de16-11e4-93e3-335cdfb96847.png)
![image](https://cloud.githubusercontent.com/assets/373559/7048931/12041126-de16-11e4-8f59-ad1e7f47b15d.png)

**Comment by emmenko** [comment]
@Niondir This should not be possible using the API. Can you provide the JSON you used to do that?

**Comment by gogregor** [comment]
@emmenko You can create a product with a name that is an empty string for a specific language, like {"en":""}. Maybe this is the issue here, that the merchant center interprets it as empty.

**Comment by emmenko** [comment]
Probably, but why is possible to create `{"en":""}` ?

**Comment by gogregor** [comment]
Because it is not forbidden ;)

**Comment by emmenko** [comment]
Shouldn't be forbidden then? Having a required field with an empty name it's the same as not having it, so it should fail in my opinion...

**Comment by gogregor** [comment]
It is a breaking change.

**Comment by emmenko** [comment]
Hmm, why is it a breaking change? It might be good maybe to see who is using this in the first place...

**Comment by mmoelli** [comment]
As we don't want to introduce breaking changes easily, we will follow our established process. First we'll introduce a deprecation message and monitor the behaviour. Afterwards we will disallow using empty strings. 

Until then, we will need to adjust the MC so that the empty strings doesn't cause any misbehavior there.

**Comment by schleichardt** [comment]
I think forbidding empty strings will make client logic more complex.

An empty String is common default value and not allowing it as alternative to not having a value confused a lot of developers:
http://stackoverflow.com/search?tab=relevance&q=oracle%20null%20string

**Comment by emmenko** [comment]
The MC actually correctly validates the product, since the name is empty which is a required field (as well as for required attributes). If someone has this problem he needs to use the API to change it, or better simply remove the product and create a new one with the required values.

I agree with the deprecation message.

**Comment by Niondir** [comment]
Yes, we put an empty string to the name. Same for the required custom attribute I guess.

**Comment by schleichardt** [comment]
API but not SDK related.

**Comment by Niondir** [comment]
So you moved it? Can I track the API issue somewhere?

**Comment by stmeissner** [comment]
@Niondir Can I kindly ask you to contact SPHERE support on http://support.sphere.io/?

thanks
