### ISSUE TITLE
add sync info to order query model

### ISSUE THREAD

**Issue by schleichardt** [sphereio/sphere-jvm-sdk#358]
`not syncInfo(channel(id="UUID"))`

* [x] also check if anything else is missing
* [x] add not to query tutorial with .negate and .not helper

**Comment by schleichardt** [comment]
@OlegIlyenko is this also possible:
`syncInfo(channel(id != "UUID"))`
?

**Comment by OlegIlyenko** [comment]
yes, it's a valid predicate, but it's not an equivalent of `not syncInfo(channel(id="UUID"))`
