### ISSUE TITLE
How about implementing retry with exponential backof for client?

### ISSUE THREAD

**Issue by svenmueller** [sphereio/sphere-jvm-sdk#361]
some more info:

http://en.wikipedia.org/wiki/Exponential_backoff
http://docs.aws.amazon.com/general/latest/gr/api-retries.html

**Comment by schleichardt** [comment]
Can you provide more information for the situations when to retry?

Is it about the TCP level, connection loss or HTTP (503) or both?

Currently you can inject you HttpClient instance which may have a retry configuration and you can decorate the SphereClient to retry.

**Comment by schleichardt** [comment]
duplicate
