### ISSUE TITLE
Deadinks to java doc in exceptions

### ISSUE THREAD

**Issue by sam0r** [sphereio/sphere-jvm-sdk#362]
Hi,
I just noticed that javadoc links in exceptions lead to a 404 in Github 
http://sphereio.github.io/sphere-jvm-sdk/javadoc/1.0.0-M12/io/sphere/sdk/client/ErrorResponseException.html
Would be good if one could actually find the documention for the specific error with the supplied link.

**Comment by schleichardt** [comment]
Thanks for reporting!
