### ISSUE TITLE
Search tests are flaky

### ISSUE THREAD

**Issue by lauraluiz** [sphereio/sphere-jvm-sdk#382]
They seem to randomly fail for no evident reason.

**Comment by schleichardt** [comment]
We should fix this soon.

**Comment by lauraluiz** [comment]
Unfortunately I already invested some time here with no success... I hope I can get some hints today.

**Comment by lauraluiz** [comment]
In fact, the problem is quite sure the one I thought last time. We are simply not leaving enough time for it to be indexed for every request. I guess in Travis only those slow request succeed, but in localhost most of them are slow by default. I'll fix it.
