### ISSUE TITLE
Implement messages

### ISSUE THREAD

**Issue by schleichardt** [sphereio/sphere-jvm-sdk#390]
http://dev.sphere.io/http-api-projects-messages.html

additional tasks:

* [x] enable `MessageQuery.of().withPredicate(m -> m.resource().is(order))`
* [x] document the other 2 test cases of MessageQueryTest

**Comment by schleichardt** [comment]
@mmoelli The messages endpoint is missing, should it be in 1.0.0? This endpoint consumes more time to implement.

It would be possible to gibe a solution which provides only the Java JSON representation instead of real typed Java classes. This would not take much time and still the messages endpoint is kind of usable.

**Comment by mmoelli** [comment]
@schleichardt A simple implementation should be enough for the 1.0.0 Important would be for me, that all endpoints can be accessed and no one is trying to build around the SDK because a function of the API cannot be used via the SDK. Thanks @nkuehn for this distinction, I like that.

**Comment by nkuehn** [comment]
by Michael: at least message base class can be implemented: http://dev.sphere.io/http-api-projects-messages.html#message

**Comment by nkuehn** [comment]
plus reference expansion
