### ISSUE TITLE
Extract HTTP stuff in module with fewer library deps

### ISSUE THREAD

**Issue by schleichardt** [sphereio/sphere-jvm-sdk#394]
* [x] no library dependencies
* [x] no project deps, like to common
* [x] add all HTTP verbs
* [x] separate impls from sphere context
* more tests for http client impls

**Comment by schleichardt** [comment]
@panshul007 Here you can track my progress.

**Comment by lauraluiz** [comment]
I have a wish for this: allow to extend the HTTP Methods if possible. With Lightspeed I had to copy every class only because I had to add more methods... so if it were possible it would be great :)
