### ISSUE TITLE
(sphere-common/compile:compileIncremental) javac returned nonzero exit code

### ISSUE THREAD

**Issue by schleichardt** [sphereio/sphere-jvm-sdk#395]
https://travis-ci.org/sphereio/sphere-jvm-sdk/builds/61438548

@lauraluiz Can you reproduce the error on your machine?

**Comment by lauraluiz** [comment]
Yes, I can reproduce it when executing `genDoc`.

**Comment by schleichardt** [comment]
I can't reproduce on both my machines, even if I delete the ivy cache it works fine.

@lauraluiz Can you have a look?

**Comment by schleichardt** [comment]
@hajoeichler @lauraluiz and me found the reason why the JVM SDK is red on travis and not on my machine, it is probably a bug in Javac which is fixed in jdk1.8.0_45 (my version) but travis uses 1.8.0_31.

**Comment by schleichardt** [comment]
@hajoeichler @lauraluiz  Should we solve it by adding a script for travis to install a recent version of Java 8 or wait until travis updates?

**Comment by hajoeichler** [comment]
Is the test code the problem or the production code?
If it's only the test code we can wait for travis to update and disable the test until then.

**Comment by schleichardt** [comment]
It is about compiling production code of the base module.

**Comment by hajoeichler** [comment]
This means people using Java8_u31 will face this problem in production?
Then we need to note which version of Java we demand to work correctly.

**Comment by schleichardt** [comment]
No, it is a bug of the java compiler, so users are not affected.

**Comment by hajoeichler** [comment]
Right, users get the binary, so they are save. Only possible contributors can run into it and they can find this issue then ;)

So, keep it disabled until travis updates the java version.

**Comment by schleichardt** [comment]
I try a workaround: https://github.com/travis-ci/travis-ci/issues/3259

https://github.com/sphereio/sphere-jvm-sdk/commit/d628cb7faf1b81db28ac2e5af3fec0918aaafbe8

**Comment by schleichardt** [comment]
workaround solved it.
