### ISSUE TITLE
Rename SDK Predicate to QueryPredicate

### ISSUE THREAD

**Issue by schleichardt** [sphereio/sphere-jvm-sdk#401]
The name clashes with the JDK class name, ok therefore we have packages, but we also have QuerySort so there is kind of a symmetry.

@lauraluiz What do you think?

**Comment by lauraluiz** [comment]
I also thought about this and it would make sense. For example, the equivalent of Predicate in the search API would be FilterExpression and FacetExpression, which also supports the argument of changing Predicate for QueryPredicate.
