### ISSUE TITLE
Review naming of query and search predicates

### ISSUE THREAD

**Issue by schleichardt** [sphereio/sphere-jvm-sdk#407]

**Comment by lauraluiz** [comment]
Hey it is not a headache! :laughing:
Well, what do you think about it? "price is greater than or equals 5" or "price is greater than or equal to 5"?

**Comment by schleichardt** [comment]
Maybe we should also bother @stmeissner with this.

**Comment by schleichardt** [comment]
We also can consider using the naming of assertj.

**Comment by lauraluiz** [comment]
Which is?

**Comment by schleichardt** [comment]
isGreaterThanOrEqualTo

**Comment by lauraluiz** [comment]
That's exactly the naming I proposed :P

**Comment by schleichardt** [comment]
* change name to isGreaterThanOrEqualTo
* rename isOneOf or isAnyOf to isIn
