### ISSUE TITLE
get recent changes from SPHERE.IO release notes

### ISSUE THREAD

**Issue by schleichardt** [sphereio/sphere-jvm-sdk#412]

**Comment by mmoelli** [comment]
@schleichardt Would be interesting to know what you mean with that. What's the intention here?

**Comment by schleichardt** [comment]
I need to incorporate the changes from http://dev.sphere.io/release-notes.html if nobody else did this. It is kind of a regular task.

**Comment by schleichardt** [comment]
see tickets
https://github.com/sphereio/sphere-jvm-sdk/issues/498
https://github.com/sphereio/sphere-jvm-sdk/issues/499
https://github.com/sphereio/sphere-jvm-sdk/issues/500
https://github.com/sphereio/sphere-jvm-sdk/issues/501
https://github.com/sphereio/sphere-jvm-sdk/issues/502
https://github.com/sphereio/sphere-jvm-sdk/issues/503
