### ISSUE TITLE
Design a top button

### ISSUE THREAD

**Issue by schleichardt** [sphereio/sphere-jvm-sdk#419]
Some pages like http://sphereio.github.io/sphere-jvm-sdk/javadoc/master/io/sphere/sdk/meta/CustomObjectDocumentation.html are very long, I think it would be nice to have a button to navigate to the top. Or does it more sense to a table of content which is always visible?

**Comment by schleichardt** [comment]
You can edit the html file, but it would be nice to post the markup here in this ticket.

**Comment by JulianSamarjiev** [comment]
**Added html**

<div class="to-top">
  <form action="#header">
    <input type="submit" value="BACK TO TOP" class="to-top-btn">
  </form>
</div>

**Comment by schleichardt** [comment]
```
 <a href="#page-toc" class="theme-btn">back to top</a>
```
