### ISSUE TITLE
Please provide a easy way to extend ProductReferences within queries

### ISSUE THREAD

**Issue by ahalberkamp** [sphereio/sphere-jvm-sdk#450]
Please provide a easy way to extend ProductReferences (just llke extension of productTypes)

**Comment by lauraluiz** [comment]
So we need to add to the ProductQuery DSL the expansion path for attributes references:
`masterVariant.attributes[*].value`

Thanks @ahalberkamp for reporting it!

**Comment by schleichardt** [comment]
plus ProductProjectionQuery DSL

workaround for now:

```java
ProductProjectionQuery.ofCurrent()
    .withExpansionPath(ExpansionPath.of("masterVariant.attributes[*].value"))
```

**Comment by schleichardt** [comment]
In the new version it will look like:

```java
final Query<ProductProjection> query = ProductProjectionQuery.ofStaged()
    .withPredicate(m -> m.id().is(product.getId()))
    .withExpansionPaths(m -> m.masterVariant().attributes().value())
    .toQuery();
```
