### ISSUE TITLE
[Searchendpoint] check for existence of Attributes

### ISSUE THREAD

**Issue by ahalberkamp** [sphereio/sphere-jvm-sdk#460]
Hi,
    
Currently I Missing the possibility to check if a attribute is defined or not for a Product using the Product Search Endpoint.

Example :
A Prooduct can have a "Startdate". This means that a Product should be displayed on the POP, if the products startdate is lower than "today" OR is not defined.

To Implement this availability rule, I would like to implement a facetExpression like:

```
 final FilterExpression<ProductProjection> onlineDateFilter = ProductProjectionSearch.model().allVariants().attribute().ofDateTime(Constants.Variant.ONLINE_DATE).filterBy().lessThanOrEmpty(ZonedDateTime.now());
```
Is it possble to implement this in the Searchendpoint ?            

regards Andi

**Comment by schleichardt** [comment]
@lauraluiz can you check if this is doable with an SearchPredicate.or and if we need such a helper.

**Comment by lauraluiz** [comment]
No, `or` and `isDefined` operators do not exist in the Search endpoint, only on the query. This is something that has to be implemented in the backend.

**Comment by stmeissner** [comment]
This feature request has been reported to the SPHERE.IO API developers.
As soon as the operators are supported by the API they can be implemented in the JVM SDK. 
We'll keep you updated.
