### ISSUE TITLE
[searchendpoint] Searching for the productimages and the productdescription. 

### ISSUE THREAD

**Issue by ahalberkamp** [sphereio/sphere-jvm-sdk#462]
Hi,

Can you also provide the possibility to search for the productimages and the productdescription using the searchendpoint.

Use-case:

In a Shop a product should only be shown on the pop if it has a description and image. So it would be good to have the possibility to define the following FilterExpressions:
```
 ProductProjectionSearch.model().description.filterBy().notEmpty
 ProductProjectionSearch.model().images().filterBy().notEmpty
```

best Regards

Andi

**Comment by stmeissner** [comment]
This feature request has been reported to the SPHERE.IO API developers.
As soon as the filter options are supported by the API they can be implemented in the JVM SDK. We'll keep you updated.
