### ISSUE TITLE
Integration tests for Search Endpoint

### ISSUE THREAD

**Issue by lauraluiz** [sphereio/sphere-jvm-sdk#473]
What to do?
- Like we have now, only to prove it works as expected, but not testing each single possible filter/facet/sort expression (assume API doc is correct).
- Like now, but additionally testing certain filter/facet/sort expressions more representative and assume the rest works as expected.
- Test every combination to make sure the DSL is not broken.

**Comment by schleichardt** [comment]
Is there still sth. to do? Is there sth. to do before 1.0.0?

**Comment by lauraluiz** [comment]
I have to review and add any missing tests. Also I wanted to split them into 2 different test classes.

**Comment by lauraluiz** [comment]
Test every combination to make sure the DSL is not broken <- done
