### ISSUE TITLE
Query all docu with id predicate

### ISSUE THREAD

**Issue by schleichardt** [sphereio/sphere-jvm-sdk#479]
* see internal blog post: Using "offset" or not to iteration on list of elements with the API
* "/products?limit=100&sort=id asc&query=id > $lastId" instead of using offset parameter

**Comment by yanns** [comment]
Please wait before implementing that. I am still making some tests to check my first results.

**Comment by schleichardt** [comment]
see http://sphereio.github.io/sphere-jvm-sdk/javadoc/v1.0.0-M25/io/sphere/sdk/meta/QueryDocumentation.html#pagination-for-large-offsets
