### ISSUE TITLE
method parameter type hints lacking the name

### ISSUE THREAD

**Issue by schleichardt** [sphereio/sphere-jvm-sdk#482]
![missing-names](https://cloud.githubusercontent.com/assets/1320833/8157730/31ca094a-1357-11e5-995f-75b5990993d3.png)

**Comment by schleichardt** [comment]
http://stackoverflow.com/questions/21733916/intellij-idea-insert-variable-names-in-methods

**Comment by schleichardt** [comment]
It was an IntelliJ IDEA sbt thing:

It is necessary to activate "Download sources and docs" in the SBT settings of IDEA.

**Comment by schleichardt** [comment]
FYI: @lauraluiz @butenkor @Guidofaassen

**Comment by lauraluiz** [comment]
It makes sense. That's the reason I could see it :)
