### ISSUE TITLE
Apply new meta model from query on search endpoint

### ISSUE THREAD

**Issue by schleichardt** [sphereio/sphere-jvm-sdk#504]

**Comment by schleichardt** [comment]
@lauraluiz Do you think you will be able to do it in the next sprint?

**Comment by lauraluiz** [comment]
Do we have a list of the particular changes?

**Comment by lauraluiz** [comment]
https://github.com/sphereio/sphere-jvm-sdk/issues/494

**Comment by schleichardt** [comment]
I think you need to change/add
* ProductProjectionSearch -> an impl and an interface
* change SearchDsl, needs a second type parameter for the result

**Comment by schleichardt** [comment]
https://github.com/sphereio/sphere-jvm-sdk/pull/624
