### ISSUE TITLE
Check dependency graph

### ISSUE THREAD

**Issue by schleichardt** [sphereio/sphere-jvm-sdk#509]
Experiments with Maven showed, that a lot of dependencies are fetched that should not be fetched outsite the test scope.

**Comment by schleichardt** [comment]
http://mvnrepository.com/artifact/io.sphere.sdk.jvm/sphere-models/usages

**Comment by schleichardt** [comment]
![out](https://cloud.githubusercontent.com/assets/1320833/8502157/d01d446e-21ac-11e5-90bf-910f60358206.png)

```
sbt dependency-dot
dot -Tpng sphere-jvm-sdk/target/dependencies-compile.dot > out.png
```

@OlegIlyenko Could you please have look that the dependencies are logical, clear and minimalistic?

**Comment by OlegIlyenko** [comment]
Looks good to me
