### ISSUE TITLE
Provide extended javadoc

### ISSUE THREAD

**Issue by butenkor** [sphereio/sphere-jvm-sdk#54]
Would be nice to have javadoc for each class with more detailed informations like:

- What it can do with it and why do i need that
- Description for all available methods
- Implementation examples

Something like that:
http://commons.apache.org/proper/commons-lang/javadocs/api-3.1/org/apache/commons/lang3/concurrent/BasicThreadFactory.html

**Comment by schleichardt** [comment]
Yep, we should do this.
