### ISSUE TITLE
Expand zones-References of Shippingmethods

### ISSUE THREAD

**Issue by ahalberkamp** [sphereio/sphere-jvm-sdk#566]
Hi,

For carhartt I need to fetch the "freeShippingLimit" from a Shippingmethod for a given country. For doing this, I queried the shippingmethods for this country and wanted to extract the "freeShippingLimit" from its shippingZones using that code:
```
    public Optional<MonetaryAmount> getfreeShippingLimitforCounty(CountryCode countryCode) {
        Optional<MonetaryAmount> freeShippingLimit = Optional.empty();
        if (countryCode != null) {
            List<ShippingMethod> shippingMethods = new ArrayList<ShippingMethod>();
            try {
                GetShippingMethodsByLocation query = GetShippingMethodsByLocation.of(countryCode);
                shippingMethods = sphereClient.execute(query).toCompletableFuture().get();
            } catch (InterruptedException | ExecutionException e) {
                LOG.error("Cannot load shippingMethods", e);
            }
            ShippingMethod shippingMethod = !shippingMethods.isEmpty() ? shippingMethods.get(0) : null;
            if (shippingMethod != null) {
                List<Reference<Zone>> zones = shippingMethod.getZones();
                for (Reference<Zone> zoneRef : zones) {
                    if (zoneRef.getObj().isPresent() && zoneRef.getObj().get().contains(countryCode)) {
                        List<ShippingRate> shippingRates = shippingMethod.getShippingRatesForZone(zoneRef);
                        freeShippingLimit = !shippingMethods.isEmpty() ? shippingRates.get(0).getFreeAbove() : Optional.empty();
                        break;
                    }
                }
            }
        }
        return freeShippingLimit;
    }
```
 After I executing the "Shippingmethod" query, I realized that the references to the shippingzones were not expanded and I don´t find a "withExpasionPath" method on the "GetShippingMethodsByLocation" object, to force sphere to expand the shippingzones.

 So can you please add the "withExpasionPath"-method to the "GetShippingMethodsByLocation" object?

**Comment by schleichardt** [comment]
Thanks for reporting!

Do you need a workaround now or can you what for the next release?

**Comment by ahalberkamp** [comment]
I would like to implement it within the next week... so I don´t need a urgent workaround!

**Comment by schleichardt** [comment]
@ahalberkamp 
The HTTP API does not support reference expansion for this endpoint.
There will be a JIRA issue, but for now you need to make a second call with ZoneQuery or ZoneBYIdFetch.
