### ISSUE TITLE
Keep the sort by id as default in query?

### ISSUE THREAD

**Issue by schleichardt** [sphereio/sphere-jvm-sdk#568]

**Comment by schleichardt** [comment]
@yanns Is this a bad default to always sort by id?

Sorting can be disabled with `ProductQuery.of().withSort(Collections.emptyList())`.

**Comment by schleichardt** [comment]
pro default sorting with id
* repeatable result
* less room for failure, if you use offset and limit without sort, you may miss elements or get them multiple times

contra
* due to constraints with MongoDB, in queries where the order is not important, the index cannot be used

**Comment by yanns** [comment]
I think mongo has a default sorting. Without ID, the results should be repeatable as well.
But with sorting with ID, we have more control

Another contra: sorting in mongo costs always some time.

**Comment by schleichardt** [comment]
http://docs.mongodb.org/v3.0/reference/glossary/#term-natural-order

**Comment by OlegIlyenko** [comment]
I personally would always avoid pre-defined default sorting. This gives a very expensive guarantee that results would always be sorted, regardless whether it's needed or not. I think that it will be a disservice for the our platform to enable sorting by default.

**Comment by OlegIlyenko** [comment]
To clarify: by "pre-defined default sorting" I mean guarantee of sorted results in SDK or sphere API layer (e.g. by ID, created date, or some kind of natural order). Natural order of Mongo doesn't matter at this point - on API layer we either give guarantee or say that results are given in random order every single time

**Comment by yanns** [comment]
the default sort by id kills the mongo performances.
I'd vote to remove it.

**Comment by schleichardt** [comment]
Ok, then let's remove this.

**Comment by emmenko** [comment]
@yanns so if I traverse pages with `id > lastId`, is it guaranteed that I get unique results?

**Comment by yanns** [comment]
@emmenko if you use `id > lastId` then you should sort by `id`.
the problem is that all queries are sorted by IDs, even the queries that ask for products by SKU.

**Comment by emmenko** [comment]
What do you mean? Default sorting by id is only when you traverse pages. A normal query doesn't set any sorting.

I'm talking about the node-sdk...

**Comment by yanns** [comment]
OK. then do not change the node-sdk ;)

**Comment by emmenko** [comment]
Then why did you ask me? :p

**Comment by yanns** [comment]
wrong info from @hajoeichler

**Comment by emmenko** [comment]
Ok :)
