### ISSUE TITLE
add experimental feature custom types

### ISSUE THREAD

**Issue by schleichardt** [sphereio/sphere-jvm-sdk#593]
* http://dev.sphere.io/dev/http-api-projects-custom-fields.html
* http://dev.sphere.io/dev/http-api-projects-types.html

* [x] Type
* [x] Field Definition
* [x] FieldType
    * [x] BooleanType
    * [x] StringType
    * [x] LocalizedStringType
    * [x] EnumType
    * [x] LocalizedEnumType
    * [x] NumberType
    * [x] MoneyType
    * [x] DateType
    * [x] TimeType
    * [x] DateTimeType
    * [x] ReferenceType
    * [x] SetType
* [x] TextInputHint to common
* [x] EnumValue
* [x] LocalizedEnumValue
* [x] Get Type by ID
* [x] Query Types
* [x] Create a Type
* [x] Update a Type
    * [x] changeName
    * [x] setDescription
    * [x] addFieldDefinition
    * [x] removeFieldDefinition
    * [x] changeLabel
    * [x] addEnumValue
    * [x] addLocalizedEnumValue
    * [ ] changeFieldDefinitionOrder
    * [ ] changeEnumValueOrder
    * [ ] changeLocalizedEnumValueOrder
* [x] delete
* [x] Custom
* [x] CustomField
* [ ] New Custom Fields = CustomFieldsDraft?
* [x] custom field in Categories (add to draft object/builder)
* [x] custom field update actions in Categories
* [x] custom field in Customers (add to draft object/builder)
* [x] custom field update actions in Customers
* [x] custom field in Carts (add to draft object/builder)
* [x] custom field update actions in Carts
* [x] custom field in Orders (add to draft object/builder)
* [x] custom field update actions in Orders
* [x] custom field in line items (add to draft object/builder)
* [x] custom field update actions in line items, cart and order
* [x] custom field in custom line items (add to draft object/builder)
* [x] custom field update actions in line items, cart and order
* [x] required validation (required field(
* [x] add interface Custom to the types in http://dev.sphere.io/http-api-projects-custom-fields.html#customizable-resource
* [x] check reference expansion, may update query and expansion models, see https://github.com/sphereio/sphere-jvm-sdk/issues/730
* [x] test io.sphere.sdk.types.CustomFieldsDraftBuilder#ofTypeKey

**Comment by schleichardt** [comment]
blocked, I want to include custom types in line items.

**Comment by schleichardt** [comment]
Still blocked, the line items should be available, but they are not documented.

**Comment by schleichardt** [comment]
blocked through possible bug in API.

**Comment by schleichardt** [comment]
@yanns maybe it was related to the "required" renaming.

**Comment by yanns** [comment]
what is the context?

**Comment by schleichardt** [comment]
https://gist.github.com/schleichardt/b0f29141a4d6afc73c8e
