### ISSUE TITLE
[1.0.0-M14]  id is in predicate query returns different results when calling it multiple times

### ISSUE THREAD

**Issue by MeiSign** [sphereio/sphere-jvm-sdk#620]
This is the query that we do:

    val predicate = ProductQuery.model().id().isIn(List("b26d8e75-0cf0-4000-90a8-e6b10f8e4276").asJava)
    val query = ProductQuery.of().byProductType(productTypes.offer).withPredicate(predicate)

    sphereClient.execute(query)

If we make this call multiple times most of the times we get the expected result but in some case we receive this errortext:

    "io.sphere.sdk.client.ErrorResponseException: SDK: 1.0.0-M14\nproject: video-99\nendpoint: GET /products?where=id+in+%28%22b26d8e75-0cf0-4000-90a8-e6b10f8e4276%22%29&sort=id+asc\nJava: 1.8.0_45\ncwd: /usr/share/neeedo-api\ndate: Tue Jul 28 15:05:29 EDT 2015\nsphere request: QueryDslImpl{predicate=Optional[Predicate[id in (\"b26d8e75-0cf0-4000-90a8-e6b10f8e4276\")]], sort=[SimpleQuerySort[sphereSortExpression=id asc]], expand=[], additionalQueryParameters=[], limit=Optional.empty, offset=Optional.empty, endpoint='/products', resultMapper=io.sphere.sdk.queries.QueryDslBuilder$$Lambda$4/1115170891@5c4623f5, readablePath=/products?where=id in (\"b26d8e75-0cf0-4000-90a8-e6b10f8e4276\")&sort=id asc, request=HttpRequestIntent[httpMethod=GET,path=/products?where=id+in+%28%22b26d8e75-0cf0-4000-90a8-e6b10f8e4276%22%29&sort=id+asc,headers={},body=Optional.empty]}\nhttp request: HttpRequestIntent[httpMethod=GET,path=/products?where=id+in+%28%22b26d8e75-0cf0-4000-90a8-e6b10f8e4276%22%29&sort=id+asc,headers={},body=Optional.empty]\nhttp response: HttpResponseImpl[statusCode=400,headers={Transfer-Encoding=[chunked], Server=[nginx], Access-Control-Allow-Origin=[*], X-Served-By=[app08.sphere.prod.commercetools.de], X-Correlation-ID=[nginx-42953316-1002-42c9-a26b-ee57aa33a605], Access-Control-Allow-Methods=[GET, POST, DELETE, OPTIONS], Connection=[close], X-Served-Config=[sphere-projects-ws-1.0], Date=[Tue, 28 Jul 2015 19:05:29 GMT], Access-Control-Allow-Headers=[Accept, Authorization, Content-Type, Origin], Content-Type=[application/json; charset=utf-8]},responseBody=Optional[[B@23949bf],associatedRequest=Optional.empty,bodyAsStringForDebugging=Optional[{\"statusCode\":400,\"message\":\"Malformed parameter: where: Invalid query field: id\",\"errors\":[{\"code\":\"InvalidInput\",\"message\":\"Malformed parameter: where: Invalid query field: id\"}]}]]\nadditional notes: []\nJavadoc: http://sphereio.github.io/sphere-jvm-sdk/javadoc/v1.0.0-M14/io/sphere/sdk/client/ErrorResponseException.html\n"
}

But we are not changing the data while we are doing these calls so it should always be able to return the correct results actually. Any ideas what we are doing wrong or is this maybe a bug with the predicate query?

**Comment by MeiSign** [comment]
We replaced our code with this query:

    Future.sequence {
        List("b26d8e75-0cf0-4000-90a8-e6b10f8e4276") map sphereClient.execute(ProductByIdFetch.of(id.value))
    }

And this returns always the expected result

**Comment by schleichardt** [comment]
Thanks for reporting, I could reproduce the problem on the API playground (https://impex.sphere.io/playground) so it is a platform related thing. I wrote to the support.

By the way, `withPredicate` deletes all previous predicates like for the product type in `ProductQuery.of().byProductType(productTypes.offer).withPredicate(predicate)`.

**Comment by schleichardt** [comment]
The issue is resolved in the platform.

**Comment by MeiSign** [comment]
Awesome, thanks a lot :)
