### ISSUE TITLE
Check how to hide search/query classes

### ISSUE THREAD

**Issue by lauraluiz** [sphereio/sphere-jvm-sdk#627]
In particular, `DefaultModelQueryModelImpl` and `SearchModelImpl` are public, they should be package-scope.

**Comment by lauraluiz** [comment]
https://github.com/sphereio/sphere-jvm-sdk/issues/604

**Comment by schleichardt** [comment]
DefaultModelQueryModelImpl is now ResourceQueryModelImpl, but I think it needs to be public since a lot of endpoint extend this class. SearchModelImpl is just used by ProductProjectionSearch.

**Comment by schleichardt** [comment]
I think they both cannot be in package scope since they are needed in at least two packages.
