### ISSUE TITLE
Improve search DSL for facets

### ISSUE THREAD

**Issue by lauraluiz** [sphereio/sphere-jvm-sdk#638]
- Make it explicit how to use set facets
- Make sure they are returning the correct type

**Comment by lauraluiz** [comment]
Connects #719

**Comment by schleichardt** [comment]
This will not be done until Friday, right?

**Comment by lauraluiz** [comment]
Half of it won't be done after post 1.0.0 (#719, "Make sure they are returning the correct type"). The other one it's just copying and pasting some methods... I was planning on doing it I refactored all the model, which I just finished doing. So I'll do it now and I close this issue to leave only #719 open.
