### ISSUE TITLE
Add a troubleshooting guide

### ISSUE THREAD

**Issue by schleichardt** [sphereio/sphere-jvm-sdk#643]
* [x] update Jackson to a current version, especially in Maven force version (toplevel pom needs explicit Jackson lib dependency)
* [x] AHC version check
* [x] log file flooding disable, async http client is chatty
* [x] Java version
* [x] os
* [ ] which data do we need before contact commercetools, provide 3 good examples

**Comment by schleichardt** [comment]
http://maven.apache.org/guides/introduction/introduction-to-dependency-mechanism.html#Transitive_Dependencies

**Comment by nkuehn** [comment]
Concerning the last bullete (what do you have to send) we could think about building a little debug function that takes the exception, collects information about the system environment etc and writes all that into a file that people can attach to the support issue.

**Comment by schleichardt** [comment]
Yes, that was the idea.
