### ISSUE TITLE
PagedResult with count

### ISSUE THREAD

**Issue by lauraluiz** [sphereio/sphere-jvm-sdk#698]
I think the `count` attribute from the platform is ignored because we have the same information counting the size of results, which is more reliable. But `count` is also really useful for testing (you don't have to simulate 25 products, but just putting `count: 25`) and in some implementations is less expensive to access `count` than calculating the size of the list.

Can we reconsider it?

**Comment by schleichardt** [comment]
would that help?

```java
PagedQueryResult.of(Collections.nCopies(25, null))
```

**Comment by lauraluiz** [comment]
Not completely. Actually that's kind of what I was doing: https://github.com/sphereio/sphere-sunrise-dmexco/blob/master/product-catalog/test/productcatalog/pages/PaginationDataFactoryTest.java#L107-L113 but it feels quite hacky.

Luckily I found PagedResult can be implemented (PagedSearch/Query/etc/Result can't) and I can simply generate the copies, but the alternative solution was with JSON, which was simply not viable.

Let's close this for now. I think the most important is that we can implement all products via interfaces and avoiding JSON (sometimes it is useful, but it's really inflexible when it comes to testing edge cases).
