### ISSUE TITLE
Create Spring MVC example with the JVM SDK

### ISSUE THREAD

**Issue by schleichardt** [sphereio/sphere-jvm-sdk#706]
see also #7

**Comment by schleichardt** [comment]
@markuslamm After Donut we need a *small* application with Spring DI and Spring MVC which shows products. It should not be like Sphere Donut.

@nkuehn here is your place for wishes

**Comment by nkuehn** [comment]
@schleichardt thank you :-).  My _opinion_ (no absolute thruths):
 * outcome ideally a library with docs, not just a project
 * spring boot should be optional / an example, but not required (it's opinionated and most spring use cases are integrations into other systems that have their own bootstrapping)
 * I personally wouldn't use XML for the example, but it has advantages, too (makes clearer what's code and what's config)
 * if MVC included, shouldn't hardwire a specific template engine outside the example
 * so, positively, what comes to my mind is:  A (singleton?) client via DI, Security integration?  Spring Cache pattern? Transactions?  Some basic MVC example (fetch a POP)?

**Comment by yanns** [comment]
We could use the JSR 330 annotations so that Spring/Guice/Scaladi could use the SDK.

**Comment by nkuehn** [comment]
@yanns nice! Really didn't know that JSR yet.   @schleichardt would it fit the scope of the SDK to provide a JSR 330 configurable Client (wrapper?) directly into the SDK?

**Comment by schleichardt** [comment]
@yanns And how? I don't exactly understand what I should do.

**Comment by yanns** [comment]
@schleichardt just annotate the classes that can be injected.
For example: https://github.com/playframework/playframework/blob/master/framework%2Fsrc%2Fplay-java-ws%2Fsrc%2Fmain%2Fjava%2Fplay%2Flibs%2Fws%2Fning%2FNingWSAPI.java#L20

**Comment by schleichardt** [comment]
So it would be just for the impls to make them singleton?

**Comment by schleichardt** [comment]
But that is not true in a multi project case.

**Comment by nkuehn** [comment]
That's why I thought about wrappers that represent a Service, we could provide one Singleton one and one that's just a DI-able Client but needs to be registered and adressed with a project name.

**Comment by yanns** [comment]
@schleichardt they must not be singleton. It was only an example.

**Comment by schleichardt** [comment]
repo: https://github.com/sphereio/commercetools-spring-demo

**Comment by markuslamm** [comment]
Hello @schleichardt , @yanns, @nkuehn, @hajoeichler, 
while working on the commercetools-spring-demo, I had the idea of a "more frameworky thing", so I decided to build a Spring Boot starter for SPHERE.IO. You can find it on https://github.com/markuslamm/sphere-spring-boot

What I thought about was, that it would be nice as a customer who uses Spring, to be able to run a simple shop application just by adding a sphere-spring-boot-starter.jar to your dependencies. 

A default configuration in the starter is setting up the minimal required Spring context, which provides a ready-to-run shop application with an embedded tomcat container. Required default Sphere services(CartService, ProductService...) will be created in the starter context, but can be replaced with custom implementations in our own app(see sampleapp). The same applies for controllers, e.g. IndexController. There're the annotations @SphereService and @SphereController, that will be processed on context startup an register the shop components in an internal ComponentRegistry.

Maybe you can have a look at it and tell me about your opinion and ideas...

**Comment by schleichardt** [comment]
I think this is a good sign that you care much and develop ideas. I also have a lot of toy projects.

This issue is about a hello world copy template as *application* with everything that happens concernings sphere and spring should be here - it is then explicit and easy to discover. It is about understanding and not reuse and DRY.
Creating a *library* is for another task in another repository. maybe next year.

After finishing Donut and this little example we have a *lot* to do in Sunrise to do the frameworky thingy that you have in mind for spring.

**Comment by schleichardt** [comment]
I think some services are not spring/JEE related so they could be JVM SDK lib without framework dependencies and therefore could be used with Play and spring.

**Comment by nkuehn** [comment]
sorry, I don't feel safe enough in the Spring stuff to offer a qualified opinion here.  
I agree with Michael @schleichardt  that we / you need to be very careful in separating the goals of a) a reusable "library" part and a staightforward copy-and-run template with no extra own abstractions. 

Anything that's targeted towards reusability / "library" should not fire up a tomcat, bind an HTTP port itself etc. 

I will be at a client site for a two day workshop in the next weeks who has a large Spring-based web infrastructure and wants to integrate Spring.  @markuslamm  if you have specific things that would interest you from their requirements and setup just drop me a PM.

**Comment by yanns** [comment]
@mitsch2000 Maybe somebody from the rewe team can have a look at it as they are using spring boot.

**Comment by hajoeichler** [comment]
Very good idea @yanns. But I suggest to interview our friends from the rewe wineshop here. I will create the contact link...
