### ISSUE TITLE
idea: a module to import sphere data

### ISSUE THREAD

**Issue by schleichardt** [sphereio/sphere-jvm-sdk#726]
So the idea is, you checkout a shop template, set credentials and then use sbt shell to import data, like example data for Donut, Sunrise, whatever.

No need to install another stack, like nodejs.

**Comment by schleichardt** [comment]
@hajoeichler @lauraluiz @nkuehn  What do you think?

**Comment by nkuehn** [comment]
Well, I'm the wrong person to ask.  My love for sbt is rather limited.  

But even if I loved sbt:  We already have a hard time maintaining and keeping the node based commandline importers up to date and complete, so I don't believe that trying to maintain a duplicate implementation without dedicated manpower will not result in happy users.

**Comment by schleichardt** [comment]
I think it already requires a lot of steps to start with sphere and Java:

1. create a merchant center account
1. create a sphere project
1. fork a template/demo, start from scratch
1. install Java tooling like JDK 8 and Maven (sbt is directly available in the templates)
1. enter credentials in a file/wizard/environment arg
1. install nodejs stack
1. import data
1. deploy the shop

Especially for donut it would be so simple.
The sbt stuff won't be much, the import stuff would be in Java and also could be separated from sbt.
I would love to reduce the effort as much as possible. Often stuff is rated how easy you can start with it.

**Comment by nkuehn** [comment]
ah, maybe I got you wrong.  If your goal is "just" the bootstrapping of a new, empty project and not the ongoing data import / export / synchronizations in a production project the idea may be feasible.  

But I would not bind it to sbt but provide the functionality library-level, i.e. as some extension to the SDK so that non-sbt environments can use it, too.

**Comment by schleichardt** [comment]
Exactly.

It would be like `sbt runMain io.sphere.donut.ImportMain` and then it deletes the merchant center created default data and creates the one product type and product for Donut. So this is not very sbt specific to run a main method.

**Comment by nkuehn** [comment]
but then it should also set up the necessary minimal tax categories,
shipping rates etc that are often forgotten and then break demos.  :-)

2015-09-18 22:09 GMT+02:00 Michael Schleichardt <notifications@github.com>:

> Exactly.
>
> It would be like sbt runMain io.sphere.donut.ImportMain and then it
> deletes the merchant center created default data and creates the one
> product type and product for Donut. So this is not very sbt specific to run
> a main method.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sphereio/sphere-jvm-sdk/issues/726#issuecomment-141553957>
> .
>



-- 
Nikolaus Kühn
Partner Enablement Manager

nikolaus.kuehn@commercetools.com
Phone: +49 172 2873 155 <+491722873155>
Twitter: @nikolausku <https://twitter.com/nikolausku>
Adams-Lehmann-Str. 44, 80797 München

-- 


[image: commercetools logo] <http://www.commercetools.com/>

Amtsgericht München, HRB 161496
Geschäftsführer: Denis Werner, Dirk Hörig, Dr. Robert Zores

www.commercetools.com
<http://www.commercetools.com/de/dmexco/>

**Comment by schleichardt** [comment]
:+1:

**Comment by hajoeichler** [comment]
Sound like a nice idea to support this specific case.
But my vision goes one step further. You just select a template by one click in the MC and everything should be done automagically from your list above. As this a rather future idea, I am fine with a reduce list for now for our demo shops. But therefore I would create specific tasks in the corresponding repos, or?

**Comment by schleichardt** [comment]
I like the mc idea because the other tech stacks like PHP would benefit from it, but then there is still open how to do this in a batch command for example for tests. So then this mc functionality should be one component which you can use with the node stack or docker.

**Comment by hajoeichler** [comment]
Good point. We need this functionality independent of the UI. You are right.

**Comment by schleichardt** [comment]
@lauraluiz @hajoeichler I think this would be great task to show some commercetools JVM SDK + Spring Batch code.

**Comment by schleichardt** [comment]
An optimistic estimation is 3 days to import categories (I already have for this code) and product types/products.
I would directly program it in the Sunrise data repository.

**Comment by schleichardt** [comment]
we will track the progress here: https://github.com/sphereio/commercetools-sunrise-data
