### ISSUE TITLE
Payment

### ISSUE THREAD

**Issue by schleichardt** [sphereio/sphere-jvm-sdk#768]
* http://dev.sphere.io/http-api-projects-payments.html
* http://dev.sphere.io/http-api-projects-orders.html#payment-info
* http://dev.sphere.io/http-api-projects-orders.html#order payment info field

subtasks:

* [x] Payment
* [x] PaymentMethodInfo
* [x] PaymentStatus
* [x] Transaction
* [x] Payment Draft + builder
* [x] Get Payment by ID
* [x] Get Payment by ID test
* [x] Query Payments
* [x] Query Payments test
* [x] Create a Payment
* [x] Create a Payment test
* [x] Update a Payment (only the command)
* [x] setCustomer
* [x] setCustomer test
* [x] setExternalId
* [x] setExternalId test
* [x] setInterfaceId test
* [x] setAuthorization
* [x] setAuthorization test
* [x] setAmountPaid
* [x] setAmountPaid test
* [x] setAmountRefunded
* [x] setAmountRefunded test
* [x] setMethodInfoInterface
* [x] setMethodInfoInterface test
* [x] setMethodInfoMethod
* [x] setMethodInfoMethod test
* [x] setMethodInfoName
* [x] setMethodInfoName test
* [x] setCustomField
* [x] setCustomField test
* [x] setCustomType
* [x] setCustomType test
* [x] setStatusInterfaceCode
* [x] setStatusInterfaceCode test
* [x] setStatusInterfaceText
* [x] setStatusInterfaceText test
* [x] transitionState
* [x] transitionState test
* [x] addTransaction test
* [x] Delete a Payment
* [x] Delete a Payment test
* [ ] check MVP requirements from Payments HipChat room
* [x] report enumeration not sphere ideomatic
* [x] update actions cart
* [x] update actions order

**Comment by schleichardt** [comment]
@cneijenhuis  paymentMethodInfo is an optional field in a payment?

**Comment by schleichardt** [comment]
Transaction Type is not a typical sphere enumeration like OrderState @cneijenhuis 

They do not contain underscores and are camel cased and start with an uppercase letter.

**Comment by cneijenhuis** [comment]
`paymentMethodInfo` and `paymentStatus` are optional in the draft, but not when returned from the API. I will fix the JSON Schema.

@nkuehn had a reason why he wanted to have the enumeration like this, but I don't remember.

**Comment by schleichardt** [comment]
@cneijenhuis in PaymentDraft for custom, I have the type CustomFieldsDraft which can be constructed with typeKey or TypeId. It is the same as in CategoryDraft and CartDraft. Can we move to this type instead of the two special types?

**Comment by cneijenhuis** [comment]
If I understand the question correctly, you want to use `CustomFieldsDraft` everywhere instead of creating a special type each for Payment, Category and Cart, correct?
If so, yes :)

**Comment by schleichardt** [comment]
Yep, reuse in API plus SDK.

**Comment by cneijenhuis** [comment]
You can also have a look at the non-inlined schema to see where we re-use things in JSON Schema. E.g. in the Payment Draft, we reference the same file `custom-fields-cmd.schema.json` as in Category.

https://api.sphere.io/documentation/json-schema/payment-create.schema.json
https://api.sphere.io/documentation/json-schema/category-create.schema.json

(For the docs we use the inlined version: https://api.sphere.io/documentation/json-schema/inline/payment-create.schema.json)

**Comment by nkuehn** [comment]
@cneijenhuis @schleichardt  the uppercase "constant style"  enumeration values are really not sphere-idiomatic.  The background is that it was originally planned as an open text field with documented  conventional values, so I chose the uppercase notation fort the value examples. 
We then changed it to a fixed Enum.   Consequentionally they should actually be CT-style like Michael proposes. 

@cneijenhuis create a backend issue before it's too late?  can we find out whether someone already uses them?    
(@mmoelli  FYI )

**Comment by cneijenhuis** [comment]
I don't think anyone seriously uses it yet, but we have some people who wrote some tests. I can change it. @mmoelli what do you think?

**Comment by hajoeichler** [comment]
+1 to align code style.

**Comment by mmoelli** [comment]
In general we can change it because we marked it as BETA. I'd also favour unified typologies within the platform. @cneijenhuis maybe you can do a quick research about projects which already have payments including transactions. At least we can contact clients then.

**Comment by schleichardt** [comment]
@cneijenhuis Is it intended that I can't query for `paymentStatus.interfaceCode` and for `paymentStatus.interfaceText`?

**Comment by cneijenhuis** [comment]
After last weeks discussion I opened a PR that will make all fields queryable. Not merged yet, sorry.

**Comment by schleichardt** [comment]
@cneijenhuis Can you notify when this pull request and for the status enumeration (all payment pull requests) are in production? I am almost done and would put this issue on blocked and continue other work.

**Comment by cneijenhuis** [comment]
Awesome!
I'll let you know when the deployment is through.

**Comment by cneijenhuis** [comment]
It's deployed :+1:

**Comment by schleichardt** [comment]
Really? I expected my tests fail due to the change of API but they are still green.

**Comment by cneijenhuis** [comment]
Which ones? I accept both `CHARGE` and `Charge` for the time being as we have one customer using that already.

**Comment by schleichardt** [comment]
:+1: Ok, I expected only "Charge" was allowed.

**Comment by schleichardt** [comment]
Ok, I am done so far. Tomorrow I will review my own pull request, then I ask if Christoph wants to review it and then it goes to Laura. So it is very likely that the features will be released this week with 1.0.0-M19.

**Comment by cneijenhuis** [comment]
:tada: great! Thanks for your effort :sunglasses:

**Comment by nkuehn** [comment]
thank you!
