### ISSUE TITLE
Add centAmount helper for MoneyImpl

### ISSUE THREAD

**Issue by schleichardt** [sphereio/sphere-jvm-sdk#789]
* name it sphere cent amount, because it uses just 2 digits after the decimal separator
* http://mavenbrowse.pauldoo.com/central/javax/money/money-api/0.8/money-api-0.8-javadoc.jar/-/javax/money/CurrencyUnit.html#getDefaultFractionDigits%28%29

```
monetaryAmount.getNumber().numberValue(BigDecimal.class).multiply(
new BigDecimal(100)//TODO maybe 100 is not true for all currencies
).setScale(0, RoundingMode.HALF_EVEN).longValue()
```

* [x] use this in MoneyRepresentation for JsonUtil
* [x] improve money formatting documentation
* [x] improve money of cents method
* [x] tests with yen

**Comment by sebbulon** [comment]
as discussed instead of multiplying by 100, can you plese multiply by `10^fractionDigits` to convert it to CTP `centAmount`? thanks
totally pseudo coding here:

```
monetaryAmount.getNumber().numberValue(BigDecimal.class).multiply(
new BigDecimal(10).pow(monetaryAmount.getDefaultFractionDigits())_//TODO maybe 100 is not true for all currencies
).setScale(0, RoundingMode.HALF_EVEN).longValue()
```

test cases:
1. one "standard" currency like Euro where 1 EUR = 100 centAmount
2. Yen, where 1 Yen = 1 centAmount
3. BTC - where 1 BTC = 100 000 000 centAmount

**Comment by cneijenhuis** [comment]
IMO this should be built-in into the MonetaryAmount class. Apparently the JSR is already final. I also like how there is no way to contact anyone there with suggestions except email the lead.

**Comment by schleichardt** [comment]
https://github.com/JavaMoney/jsr354-ri/blob/1.0/src/test/java/org/javamoney/moneta/function/MonetaryQueriesTest.java#L21

```java
	@Test
	public void shouldConvertMinorPart(){
		MonetaryAmount money = Money.parse("EUR 2.35");
		Long result = money.query(MonetaryQueries.convertMinorPart());
		assertEquals(result, Long.valueOf(235L));
	}
```

**Comment by schleichardt** [comment]
There is more cool stuff, so for example extract the part before and after the decimal separator.

**Comment by sebbulon** [comment]
aha right - no need to custom code then!

**Comment by cneijenhuis** [comment]
That is the function I have been looking for, thanks. But `MonetaryQueries` is part of moneta and not of javax.money, as far as I can see. Moneta is also not available when I add the JVM SDK in the pom. Guess I gotta add it...

**Comment by schleichardt** [comment]
Moneta is a dependency of the JVM SDK, it should be there.

https://github.com/sphereio/sphere-jvm-sdk/blob/master/project/Build.scala#L80
https://github.com/sphereio/sphere-jvm-sdk/blob/master/project/Libs.scala#L38

**Comment by cneijenhuis** [comment]
![screen shot 2015-10-14 at 11 12 29](https://cloud.githubusercontent.com/assets/2638512/10479422/90ccecd4-7264-11e5-80f6-1eaae520ecca.png)
Okay, I can import other stuff from Moneta (so it is in the JVM SDK), but not MonetaryQueries. Apparently it has been added after the 1.0 release on 10 of April, and there seems to be no newer release...

**Comment by schleichardt** [comment]
Can you try this?

```java
        final MonetaryAmount amount = MoneyImpl.of(new BigDecimal("1234.56"), EUR);

        final Long centAmount = amount.query(MonetaryUtil.minorUnits());

        assertThat(centAmount).isEqualTo(123456);
```

**Comment by cneijenhuis** [comment]
That works :+1: Thanks!

**Comment by cneijenhuis** [comment]
I guess in `MoneyImpl.ofCents` it should be something like:
```java
public static MonetaryAmount ofCents(final long centAmount, final CurrencyUnit currencyUnit) {
    return of(new BigDecimal(centAmount).divide(new BigDecimal(10).pow(currencyUnit.getDefaultFractionDigits())), currencyUnit);
}
```

**Comment by cneijenhuis** [comment]
thanks! :tada:
