### ISSUE TITLE
obfuscate all personal data of customers in log outputs

### ISSUE THREAD

**Issue by stmeissner** [sphereio/sphere-jvm-sdk#800]
similar to issue #767, please obfuscate all data in logs that could refer to customer's identity, like name, gender, email address, phone number, postal address, etc.
only log them on DEBUG level

**Comment by schleichardt** [comment]
example log: https://gist.github.com/schleichardt/b91af3f7e17f4a3e82bf

**Comment by schleichardt** [comment]
I documented on "Checklist for Commercetools Platform Shops" that the logger "sphere.customers" should be set to WARN or ERROR.
