### ISSUE TITLE
Merge AttributeType/FieldType

### ISSUE THREAD

**Issue by lauraluiz** [sphereio/sphere-jvm-sdk#849]
Is it possible to reuse the same AttributeTypes for ProductTypes and CustomTypes? They have exactly the same name and the similar meaning, and they are giving conflicts when using them together. It is true that is not very likely to be used together in the same class except for simple projects, but therefore it makes it a bit difficult to create a demo project.

**Comment by schleichardt** [comment]
Yes, we already discussed this with @yanns 

The two AttributeTypes can evolve differently so they should be different classes. I also think it is not so usable to have two classes of the same name in one library, but the others said it is okay.

So I would not go for making them same class, but what alternatives do we have?

**Comment by schleichardt** [comment]
I changed the milestone to RC1 since this is a question we should solve before the final release.

**Comment by lauraluiz** [comment]
If they cannot be merged, I would suggest to change the same from StringType to `StringAttributeType`, because any other name options sounds wrong (i.e. `StringProductType`, `StringProductAttribute`).
To make it all coherent, then for Custom Fields should be `StringFieldType`.

The change would be a double win: not only clearly separates Attribute from Custom Types, but it also makes it much easier to discover them, since now you start typing `AttributeType` or `FieldType` and see nothing, while if we use the correct suffix many IDEs would help.

And I think it is important to change this, I just spent a lot more of time that I wanted to, to solve this issue. And for newcomers it is difficult to discover them, their only option is to look the interface and find the implementations, which is not the best way.

What do you think?

**Comment by schleichardt** [comment]
sounds like a plan :)
