### ISSUE TITLE
add typical resource ids to TypeDraftBuilder

### ISSUE THREAD

**Issue by schleichardt** [sphereio/sphere-jvm-sdk#887]
I still need to think of a good name but it should be like this:
```java
TypeDraftBuilder builder = //
builder.addCarts().addPayments().addLineItems();
```

**Comment by cneijenhuis** [comment]
Yep, good idea :+1:

**Comment by schleichardt** [comment]
@lauraluiz @cneijenhuis oops, that went directly into master, I forgot to change the branch. Can you still review it, please?

**Comment by cneijenhuis** [comment]
Looks nice! Thanks :tada:

**Comment by lauraluiz** [comment]
Yep, that's less confusing for people and they can easily find a comprehensive list of supported resources :+1:
