### ISSUE TITLE
Allow comparing addresses

### ISSUE THREAD

**Issue by lauraluiz** [sphereio/sphere-jvm-sdk#91]
It is a very common practice to compare addresses (e.g. to decide if the customer selected the option "use same shipping address as billing address"). Currently the equals method have into account the ID of the address, which will always be different. 

----

* [ ] equals includes id
* [ ] alternative method exclusive id

**Comment by schleichardt** [comment]
Can you provide a Java code example how you want the comparison look like?

**Comment by emmenko** [comment]
If you have the checkbox option, why do you need to compare addresses?

**Comment by lauraluiz** [comment]
@schleichardt just like a normal `equals` method for the class, but discarding the ID. The problem here is that the class Address contains the ID + all address fields. So the `equals` method of the class cannot be used for this purpose, since the ID is also being compared.

@emmenko when having the information in the cart, I no longer have information about the checkout options the user selected. In fact, I need to analyze this cart information in order to display the checkout options, that's one of the cases where the comparison is used.

**Comment by schleichardt** [comment]
Something like that?

```
final boolean isSame = addressOne.equalsIgnoreId(addressTwo);
//impl will be addressOne.withId(Optional.empty()).equals(addressTwo.withId(Optional.empty()))
```

**Comment by lauraluiz** [comment]
Yes, that looks like it. I don't remember where I had to do the comparison manually, but probably it was before the `with` methods were introduced, because my approach was much more complicated ;)

**Comment by emmenko** [comment]
@schleichardt how about passing a list of keys to ignore to the equals method?

```scala
def isEqual(a: Address, b: Address, ignoreKeys: Set[String] = Set.empty)

// isEqual(a, b, Set('id'))
```

@lauraluiz ok, I see...

**Comment by schleichardt** [comment]
@emmenko I also thought about passing a list of fields to compare, but if equalsIgnoreId is enough I would leave it at that.

**Comment by emmenko** [comment]
Yeah, I was thinking more to make it a general utility function.

**Comment by schleichardt** [comment]
With price now the same problem comes up, I think it is best to ignore the id in the comparison.

**Comment by schleichardt** [comment]
Okay, we create AddressDraft.

**Comment by schleichardt** [comment]
under review

**Comment by schleichardt** [comment]
The usability and maintainebility decreases a lot splitting the objects.
