### ISSUE TITLE
Correct annotation of Transaction's getState method

### ISSUE THREAD

**Issue by sesamzoo** [sphereio/sphere-jvm-sdk#914]
According to the SDK the result of Transaction's getState() is nullable, but according to the API documentation it should be nonnullable, because it returns a mandatory field.

https://github.com/sphereio/sphere-jvm-sdk/blob/master/sphere-models/src/main/java/io/sphere/sdk/payments/Transaction.java
http://dev.commercetools.com/http-api-projects-payments.html#transaction

**Comment by schleichardt** [comment]
Thanks, I will have a look.
