### ISSUE TITLE
Migrate to Maven as build tool

### ISSUE THREAD

**Issue by schleichardt** [sphereio/sphere-jvm-sdk#979]
SBT is there for historical reasons and not very contributor friendly.
Also the IDE support isn't quite well.

**Comment by schleichardt** [comment]
@lauraluiz Are you ok with this? @nkuehn would appreciate this and @hajoeichler said it would not be that difficult to migrate

**Comment by lauraluiz** [comment]
For me is okay, whatever suits better the project. As you said, we used SBT for Play, so I think Maven is a good choice now that we don't have that dependency.

**Comment by nkuehn** [comment]
gradle seems to be a pretty well accepted, too in the plain java community.  You'll have to evaluate yourself whether the build jobs would become complete XML hell in maven or not.

**Comment by schleichardt** [comment]
Actually, I am quite happy with Maven, since it is so old and widely used a lot of plugins were already available to do very useful and advanced tasks - stuff which I need to code myself with SBT. And it is so nice to open the project in any Java IDE and it just works.

**Comment by nkuehn** [comment]
great.  I just wanted to communicate that I have no hardliner opinion on the topic.

**Comment by schleichardt** [comment]
done
