### ISSUE TITLE
LocalizedToStringProductAttributeConverter public constructor

### ISSUE THREAD

**Issue by lauraluiz** [sphereio/sphere-jvm-sdk#992]
`LocalizedToStringProductAttributeConverter` class should have a public constructor (maybe static factory constructor) to allow to use it directly without needing to inherit from it (which is default behaviour). In case you want to customized some behaviour because it doesn't satisfy you, then you are more than welcome to create a subclass.

Also, add in the documentation where to obtain the reference for the product type (product).

And maybe I've already asked it, but why `LocalizedToString` prefix? I can get the strings are localized, but it makes the name painfully long, maybe we can skip the obvious parts of it unless it really makes sense (i.e. there's a non-localized converted).

**Comment by schleichardt** [comment]
LocalizedToString: it is dependent on a locale and maps to string, you can suggest a better name if you like

**Comment by lauraluiz** [comment]
I'm still thinking about better names. For a start, I would get rid of the `Localized` part because that's something you always need to handle a particular type of attributes, so it's not strictly part of the converter.

I would also start with some word that lets me find the class faster (I would never think of finding it by the name of `LocalizedToString`).

Then it would be great to find an equivalent of `LocalizedToStringConverter`, i.e. "a converter that transforms to text", with a single word.

In Java world, `Formatter` would be a similar class (https://docs.oracle.com/javase/7/docs/api/java/util/Formatter.html) and `ProductAttributeFormatter` sounds good in size and searchability. I don't know if somebody can come up with a better name for that.

**Comment by schleichardt** [comment]
How about DefaultProductAttributeFormatter? I also want to be able to create a stereotype for this.

**Comment by lauraluiz** [comment]
If you plan on creating others, I guess it's okay. Just make sure we really need it :)
